# Generated by Django 6.0 on 2026-01-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='discussions.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
